kind: ConfigMap
apiVersion: v1
metadata:
  # Must match the 'spring.application.name' property of the application
  name: organization-service-0
data:
  application.yml: |-
    organization:
      message: Say Hello to the World (organization-service-0)
      username: Alexander
    ---
    spring:
      profiles: development
    organization:
      message: Say Hello to the Developers (organization-service-0)
