kind: ConfigMap
apiVersion: v1
metadata:
  name: organization-service
data:
  application.yml: |-
    organization:
      message: Say Hello to the World (organization-service)
      username: Alexander
    ---
    spring:
      profiles: development
    organization:
      message: Say Hello to the Developers
    ---
    spring:
      profiles: production
    organization:
      message: Say Hello to the Production
  profile: development
