spec:
  template:
    spec:
      serviceAccountName: "qs-organization-service"
      volumes:
        - name: "app-secret"
          secret:
            secretName: "organization-service"
        - name: "app-config"
          configMap:
            name: "organization-service"
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: organization-service
                  key: profile
            #"development" "production"
          volumeMounts:
            - name: "app-secret"
              readOnly: true
              mountPath: "/etc/secrets/organization-service"
            - name: "app-config"
              readOnly: true
              mountPath: "/etc/config/organization-service"
          resources:
            requests:
              cpu: "0.5"
              memory: 500Mi
            limits:
              cpu: "1.0"
              memory: 2048Mi
#          env:
#          - name: SPRING_APPLICATION_JSON
#            value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
