spring:
  application:
    name: organization-service
#server:
#  port: 8080
#management:
#  endpoint:
#    restart:
#      enabled: true
#    health:
#      enabled: true
#    info:
#      enabled: true
#contract-service:
#  ribbon:
#    eureka:
#      enabled: false
#    client:
#      enabled: true
#    listOfServers: contract-service:8085
#    ServerListRefreshInterval: 5000
